name: Auto refresh

on:
  push:
      branches:
        - main
  schedule:
    - cron: "30 11 * * *"
    
   
jobs:
  WebScraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi
        - name: Execute adlist_converter.py
        run: |
          git pull
          python .github/scripts/adlist_converter.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git push
      - name: Execute wrapper.py
        run: |
          git pull
          python .github/scripts/wrapper.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git push            
      - name: Commit all changes
        run: |
          git pull
          git commit -m "auto refresh"
          git push 
