name: jogsertowebaruhazak_1

on:
  push:
      branches:
        - main
  schedule:
    - cron: "30 11 * * *"
    
   
jobs:
  WebScraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi
      - name: Icon badge
        uses: damienaicheh/icon-badge-action@v1.0.0
        with:
          images-path: 'docs/refresh_button.png'
      - name: Execute py script 1
        run: |
          python .github/scripts/jogsertowebaruhazak_1.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute py script 2
        run: |
          python .github/scripts/jogsertowebaruhazak_2.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute py script 3
        run: |
          python .github/scripts/questionable_sources.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          
      - name: Merge all lists to one file
        run: |
          python .github/scripts/wrapper.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      
      - name: Commit all changes
        run: |
          git commit -m "auto refresh"
          git push 
