name: Auto refresh

on:
  push:
      branches:
        - main
  schedule:
    - cron: "30 11 * * *"
    
   
jobs:
  WebScraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          if [ -f .github/workflows/requirements.txt ]; then pip install -r .github/workflows/requirements.txt; fi
      - name: Execute jogsertowebaruhazak_1.py
        run: |
          python .github/scripts/jogsertowebaruhazak_1.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute jogsertowebaruhazak_2.py
        run: |
          python .github/scripts/jogsertowebaruhazak_2.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute questionable_sources.py
        run: |
          python .github/scripts/questionable_sources.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute adlist_converter.py
        run: |
          python .github/scripts/adlist_converter.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute collector.py
        run: |
          python .github/scripts/collector.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
      - name: Execute getraw.py
        run: |
          python .github/scripts/getraw.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
               
      - name: Commit all changes
        run: |
          git commit -m "auto refresh"
          git push 
